name: my_solitarie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: any
  audioplayers: ^6.1.0
  shared_preferences: ^2.3.0
  google_fonts: ^6.2.1
  table_calendar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/shop_items.json
    - assets/sounds/
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/cards/
    - assets/images/figures/
    - assets/images/figures/elegant/
    - assets/images/figures/royal/
    - assets/images/figures/samurai/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"
